"""Training utilities for the EmbeddingGemma 2 reranker."""

from .collator import PairCollator, RerankerBatch, RerankerCollator
from .dataset import (
    RerankingExample,
    iter_jsonl,
    load_jsonl,
    parse_candidates,
    parse_pairwise,
    parse_record,
    save_jsonl,
    split_examples,
    write_sample_data,
)
from .hard_negatives import (
    MiningConfig,
    MiningStats,
    load_corpus,
    mine_hard_negatives,
    similarity_matrix,
    write_mined,
)
from .losses import (
    LossOutput,
    available_losses,
    bce_loss,
    compute_loss,
    distillation_kl_loss,
    listwise_loss,
    mse_loss,
    pairwise_margin_loss,
)
from .trainer import (
    FullFinetuneNotConfirmed,
    RerankerTrainer,
    TrainingSummary,
    configure_trainable,
    print_trainable_summary,
    set_seed,
)

__all__ = [
    "FullFinetuneNotConfirmed",
    "LossOutput",
    "MiningConfig",
    "MiningStats",
    "PairCollator",
    "RerankerBatch",
    "RerankerCollator",
    "RerankerTrainer",
    "RerankingExample",
    "TrainingSummary",
    "available_losses",
    "bce_loss",
    "compute_loss",
    "configure_trainable",
    "distillation_kl_loss",
    "iter_jsonl",
    "listwise_loss",
    "load_corpus",
    "load_jsonl",
    "mine_hard_negatives",
    "mse_loss",
    "pairwise_margin_loss",
    "parse_candidates",
    "parse_pairwise",
    "parse_record",
    "print_trainable_summary",
    "save_jsonl",
    "set_seed",
    "similarity_matrix",
    "split_examples",
    "write_mined",
    "write_sample_data",
]
